### ISSUE TITLE
Project template

### ISSUE THREAD

**Issue by cirillom** [lucasgpulcinelli/ICMC-assembly-preprocessor#12]
This module has a [project template](https://github.com/cirillom/icmc-assembly-template-repo) that can be used by anyone. This should be linked in the repository README.md

Is the template good enough for it?

**Comment by cirillom** [comment]
@lucasgpulcinelli @gabriel-libardi @matheuspd

**Comment by lucasgpulcinelli** [comment]
I agree the template provided is good for general use, this can be referenced in the wiki too. I can solve that in my work for #5 and #3.
