### ISSUE TITLE
Variables with underscore dont't work

### ISSUE THREAD

**Issue by matheuspd** [lucasgpulcinelli/ICMC-assembly-preprocessor#8]
While testing, it was seem that variables with underscore were not recognized by the preprocessor's regex.

**Comment by lucasgpulcinelli** [comment]
Hey @matheuspd, seems like they work as intended, the regex has a \w, translating to  [a-zA-Z0-9_], which contains the underscore character. I pointed that to you personally but forgot this fact, I don't know what kind of test I showed you that the preprocessor did not understand inside the regex (probably it had some other character that is not recognized, such as '.', and I at least don't think it should be added)
